### ISSUE TITLE
RecoverPubkey not work with ECC_CURVE_SM2_STANDARD

### ISSUE THREAD

**Issue by pip1998** [blocktree/go-owcrypt#4]
cannot work with curve `ECC_CURVE_SM2_STANDARD`
https://github.com/blocktree/go-owcrypt/blob/131509de7fb80b631557ce1c24560ffdf39bf56b/eccset.go#L405

**Recurrent**
1. run the rest in PR: #3

**Comment by heshuchao** [comment]
Sorry for taking so long to reply you, The SM2 public key recovery part is not tested because it is not used in our system. And the current process follows ecdsa's standard, which is clearly wrong.

I'll study whether SM2 supported public key recovery and fix the bug(or delete it if not support),
Thanks for let me know and sorry for the trouble this has caused you.
---------------------

抱歉这么晚才回复你， SM2的公钥恢复这一部分因为在我们系统里面一直没有用到，所以没有测试。目前的代码是和ECDSA的secp256k1共享一个流程， 所以明显是错误的。

最近我会研究一下SM2的签名流程是否支持此类公钥恢复， 如果支持会尽快修复bug，不支持会删除这部分代码。

抱歉这部分代码给你造成了困扰。

感谢告知！
